module.exports = {
    div: require('../ui/atoms/div'),
    span: require('../ui/atoms/span'),
    li: require('../ui/atoms/li'),
    h1: require('../ui/atoms/h1'),
    h2: require('../ui/atoms/h2'),
    h3: require('../ui/atoms/h3'),
    h4: require('../ui/atoms/h4'),
    h5: require('../ui/atoms/h5'),
    h6: require('../ui/atoms/h6'),
    ol: require('../ui/atoms/ol'),
    ul: require('../ui/atoms/ul'),
    nav: require('../ui/atoms/nav'),
    button: require('../ui/atoms/button'),
    form: require('../ui/atoms/form'),
    input: require('../ui/atoms/input'),
    img: require('../ui/atoms/img'),
    a: require('../ui/atoms/a'),
    svg: require('../ui/atoms/svg'),
    path: require('../ui/atoms/path'),
    i: require('../ui/atoms/i'),
}
